<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOsUEPGV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOsUEPGV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOsUEPGV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOsUEPGV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOsUEPGV\App_KernelDevDebugContainer([
    'container.build_hash' => 'OsUEPGV',
    'container.build_id' => 'a2d5bd92',
    'container.build_time' => 1590959251,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOsUEPGV');
