<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'case' => [[], ['_controller' => 'App\\Controller\\CaseController::index'], [], [['text', '/case']], [], []],
    'cause' => [[], ['_controller' => 'App\\Controller\\CauseController::index'], [], [['text', '/cause']], [], []],
    'department' => [[], ['_controller' => 'App\\Controller\\DepartmentController::index'], [], [['text', '/department']], [], []],
    'icon' => [[], ['_controller' => 'App\\Controller\\IconController::index'], [], [['text', '/icon']], [], []],
    'modality' => [[], ['_controller' => 'App\\Controller\\ModalityController::index'], [], [['text', '/modality']], [], []],
    'module' => [[], ['_controller' => 'App\\Controller\\ModuleController::index'], [], [['text', '/module']], [], []],
    'module_profile' => [[], ['_controller' => 'App\\Controller\\ModuleProfileController::index'], [], [['text', '/module/profile']], [], []],
    'municipality' => [[], ['_controller' => 'App\\Controller\\MunicipalityController::index'], [], [['text', '/municipality']], [], []],
    'nationality' => [[], ['_controller' => 'App\\Controller\\NationalityController::index'], [], [['text', '/nationality']], [], []],
    'neighborhood' => [[], ['_controller' => 'App\\Controller\\NeighborhoodController::index'], [], [['text', '/neighborhood']], [], []],
    'observatory' => [[], ['_controller' => 'App\\Controller\\ObservatoryController::index'], [], [['text', '/observatory']], [], []],
    'permission' => [[], ['_controller' => 'App\\Controller\\PermissionController::index'], [], [['text', '/permission']], [], []],
    'permission_profile' => [[], ['_controller' => 'App\\Controller\\PermissionProfileController::index'], [], [['text', '/permission/profile']], [], []],
    'person' => [[], ['_controller' => 'App\\Controller\\PersonController::index'], [], [['text', '/person']], [], []],
    'person_profile' => [[], ['_controller' => 'App\\Controller\\PersonProfileController::index'], [], [['text', '/person/profile']], [], []],
    'profession' => [[], ['_controller' => 'App\\Controller\\ProfessionController::index'], [], [['text', '/profession']], [], []],
    'profile' => [[], ['_controller' => 'App\\Controller\\ProfileController::index'], [], [['text', '/profile']], [], []],
    'scholarship' => [[], ['_controller' => 'App\\Controller\\ScholarshipController::index'], [], [['text', '/scholarship']], [], []],
    'setting' => [[], ['_controller' => 'App\\Controller\\SettingController::index'], [], [['text', '/setting']], [], []],
    'site_class' => [[], ['_controller' => 'App\\Controller\\SiteClassController::index'], [], [['text', '/site/class']], [], []],
    'variable' => [[], ['_controller' => 'App\\Controller\\VariableController::index'], [], [['text', '/variable']], [], []],
    'vehicle' => [[], ['_controller' => 'App\\Controller\\VehicleController::index'], [], [['text', '/vehicle']], [], []],
    'weapon_type' => [[], ['_controller' => 'App\\Controller\\WeaponTypeController::index'], [], [['text', '/weapon/type']], [], []],
    'zone' => [[], ['_controller' => 'App\\Controller\\ZoneController::index'], [], [['text', '/zone']], [], []],
];
